version: '3.9'

services:
  client:
    image: ${DOCKER_USERNAME}/myclient:latest
    ports:
      - "3000:3000"
    environment:
      - VITE_WS_URL=${VITE_WS_URL}
    depends_on:
      - server

  server:
    image: ${DOCKER_USERNAME}/myserver:latest
    ports:
      - "3001:3000"
    environment:
      - DB_URL=${DB_URL}
      - ClientUrl=${ClientUrl}

 
