name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push Client Image (with --build-arg)
      - name: Build and Push Client Image
        uses: docker/build-push-action@v5
        with:
          context: ./ws
          file: ./ws/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/myclient:latest
          build-args: |
            VITE_WS_URL=${{ secrets.VITE_WS_URL }} 

      # Build and Push Server Image
      - name: Build and Push Server Image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/myserver:latest

      # Set up SSH agent
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Deploy to server
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ~/app
            echo "VITE_WS_URL=${{ secrets.VITE_WS_URL }}" > .env
            echo "DB_URL=${{ secrets.DB_URL }}" >> .env
            echo "ClientUrl=${{ secrets.ClientUrl }}" >> .env
            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> .env
            docker compose pull
            docker compose down
            docker compose up -d --build
          EOF